var icons = {
  'avatar': '/static/icons/avatar.svg',
  'gallery': '/static/icons/gallery.svg',
  'home': '/static/icons/home.svg',
  'back_arrow': '/static/icons/back_arrow.svg',
  'bell': '/static/icons/bell.svg',
  'mark': '/static/icons/mark.svg',
  'bonus': '../static/icons/coins.svg',
  'basket-card': '/static/icons/basket-card.svg',
  'close': '/static/icons/close.svg',
  'checked': '/static/icons/checked.svg',
  'heart': '../static/icons/heart.svg',
  'search': '../static/icons/search.svg',
  'compare': '../static/icons/compare.svg',
  'shopping': '../static/icons/shopping-cart.svg',
  'cart': '/static/icons/cart.svg',
  'growth': '/static/icons/growth.svg',
  'arrow-thin': '/static/icons/arrow_thin.svg',
  'arrow-bold': '/static/icons/arrow-bold.svg',
  'arrow-down': '/static/icons/arrow_down.svg',
  'basket-cart': '/static/icons/basket-cart.svg',
  'chat': '/static/icons/chat.svg',
  'credit-card': '/static/icons/credit-card.svg',
  'return': '/static/icons/return.svg',
  'shipping': '/static/icons/shipping.svg',
  'phone-call': '/static/icons/phone-call.svg',
  'promotion': '/static/icons/promotion.svg',
  'vk': '/static/icons/vk.svg',
  'fb': '/static/icons/fb.svg',
  'instagram': '/static/icons/instagram.svg'
}

export default icons
